# Generated by Django 5.2 on 2025-04-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("ENROUTE", "en-route"),
                    ("PICKUP", "pickup"),
                    ("DROPOFF", "dropoff"),
                ],
                default="ENROUTE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="rideevent",
            name="id_ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="rides.ride",
            ),
        ),
    ]
