# Generated by Django 5.2 on 2025-04-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("ENROUTE", "en-route"),
                    ("PICKUP", "pickup"),
                    ("DROPOFF", "dropoff"),
                ],
                default="ENROUTE",
                max_length=50,
            ),
        ),
    ]
